<?php

namespace CR\GSBRBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GSBRController__JMSInjector
{
    public static function inject($container) {
        $instance = new \CR\GSBRBundle\Controller\GSBRController();
        return $instance;
    }
}
