<?php

namespace Proxies\__CG__\CR\GSBRBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Praticien extends \CR\GSBRBundle\Entity\Praticien implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNomMedecin($nomMedecin)
    {
        $this->__load();
        return parent::setNomMedecin($nomMedecin);
    }

    public function getNomMedecin()
    {
        $this->__load();
        return parent::getNomMedecin();
    }

    public function setPrenomMedecin($prenomMedecin)
    {
        $this->__load();
        return parent::setPrenomMedecin($prenomMedecin);
    }

    public function getPrenomMedecin()
    {
        $this->__load();
        return parent::getPrenomMedecin();
    }

    public function setAdresseMedecin($adresseMedecin)
    {
        $this->__load();
        return parent::setAdresseMedecin($adresseMedecin);
    }

    public function getAdresseMedecin()
    {
        $this->__load();
        return parent::getAdresseMedecin();
    }

    public function setCpMedecin($cpMedecin)
    {
        $this->__load();
        return parent::setCpMedecin($cpMedecin);
    }

    public function getCpMedecin()
    {
        $this->__load();
        return parent::getCpMedecin();
    }

    public function setVilleMedecin($villeMedecin)
    {
        $this->__load();
        return parent::setVilleMedecin($villeMedecin);
    }

    public function getVilleMedecin()
    {
        $this->__load();
        return parent::getVilleMedecin();
    }

    public function setCoefNotoriete($coefNotoriete)
    {
        $this->__load();
        return parent::setCoefNotoriete($coefNotoriete);
    }

    public function getCoefNotoriete()
    {
        $this->__load();
        return parent::getCoefNotoriete();
    }

    public function setTypeMedecinId($typeMedecinId)
    {
        $this->__load();
        return parent::setTypeMedecinId($typeMedecinId);
    }

    public function getTypeMedecinId()
    {
        $this->__load();
        return parent::getTypeMedecinId();
    }

    public function setTypeMedecin(\CR\GSBRBundle\Entity\Type_praticien $typeMedecin = NULL)
    {
        $this->__load();
        return parent::setTypeMedecin($typeMedecin);
    }

    public function getTypeMedecin()
    {
        $this->__load();
        return parent::getTypeMedecin();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nomMedecin', 'prenomMedecin', 'adresseMedecin', 'cpMedecin', 'villeMedecin', 'coefNotoriete', 'typeMedecin');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}