<?php

namespace Proxies\__CG__\CR\GSBRBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Medicament extends \CR\GSBRBundle\Entity\Medicament implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDepotLegal($depotLegal)
    {
        $this->__load();
        return parent::setDepotLegal($depotLegal);
    }

    public function getDepotLegal()
    {
        $this->__load();
        return parent::getDepotLegal();
    }

    public function setNomCommercial($nomCommercial)
    {
        $this->__load();
        return parent::setNomCommercial($nomCommercial);
    }

    public function getNomCommercial()
    {
        $this->__load();
        return parent::getNomCommercial();
    }

    public function setIdFamille($idFamille)
    {
        $this->__load();
        return parent::setIdFamille($idFamille);
    }

    public function getIdFamille()
    {
        $this->__load();
        return parent::getIdFamille();
    }

    public function setComposition($composition)
    {
        $this->__load();
        return parent::setComposition($composition);
    }

    public function getComposition()
    {
        $this->__load();
        return parent::getComposition();
    }

    public function setEffets($effets)
    {
        $this->__load();
        return parent::setEffets($effets);
    }

    public function getEffets()
    {
        $this->__load();
        return parent::getEffets();
    }

    public function setContreIndication($contreIndication)
    {
        $this->__load();
        return parent::setContreIndication($contreIndication);
    }

    public function getContreIndication()
    {
        $this->__load();
        return parent::getContreIndication();
    }

    public function setPrixEchantillon($prixEchantillon)
    {
        $this->__load();
        return parent::setPrixEchantillon($prixEchantillon);
    }

    public function getPrixEchantillon()
    {
        $this->__load();
        return parent::getPrixEchantillon();
    }

    public function setFamille(\CR\GSBRBundle\Entity\Famille $famille = NULL)
    {
        $this->__load();
        return parent::setFamille($famille);
    }

    public function getFamille()
    {
        $this->__load();
        return parent::getFamille();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'depotLegal', 'nomCommercial', 'composition', 'effets', 'contreIndication', 'prixEchantillon', 'Famille');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}